{{- if .Values.global.externalClickHouse.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-external-clickhouse
spec:
  ports:
  - name: tcp-port
    port: 9000
    targetPort: tcp-port
    protocol: TCP
  - name: http-port
    port: 8123
    targetPort: http-port
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Chart.Name }}-external-clickhouse
subsets:
{{- range .Values.global.externalClickHouse.hosts }}
- addresses:
  - ip: {{ tpl (toString .ip) $ }}
  ports:
  - name: tcp-port
    port: {{ tpl (toString .tcpPort) $ }}
    protocol: TCP
  - name: http-port
    port: {{ tpl (toString .httpPort) $ }}
    protocol: TCP
{{- end }}
{{- end }}
