{{- if and (eq .Values.mode "deployment") (.Values.configMap.create) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otel-agent.fullname" . }}
  namespace: {{ template "otel-agent.namespace" . }}
  labels:
    {{- include "otel-agent.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- include "otel-agent.deploymentConfig" . | nindent 4 -}}
{{- end }}
