{{- if eq .Values.mode "deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel-agent.fullname" . }}
  namespace: {{ template "otel-agent.namespace" . }}
  labels:
    {{- include "otel-agent.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations:
    {{- range $key, $value := .Values.annotations }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "otel-agent.selectorLabels" . | nindent 6 }}
      {{- include "otel-agent.component" . | nindent 6 }}
  strategy:
    {{- if eq .Values.rollout.strategy "RollingUpdate" }}
    {{- with .Values.rollout.rollingUpdate }}
    rollingUpdate:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
    type: {{ .Values.rollout.strategy }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- include "otel-agent.podAnnotations" . | nindent 8 }}
      labels:
        {{- include "otel-agent.selectorLabels" . | nindent 8 }}
        {{- include "otel-agent.component" . | nindent 8 }}
        {{- include "otel-agent.podLabels" . | nindent 8 }}
    spec:
      {{- with .Values.dnsPolicy }}
      dnsPolicy: {{ . }}
      {{- end }}
      {{- with .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- $podValues := deepCopy .Values }}
      {{- $podData := dict "Values" $podValues "configmapSuffix" "" "isAgent" false }}
      {{- include "otel-agent.pod" ($podData | mustMergeOverwrite (deepCopy .)) | nindent 6 }}
      hostNetwork: {{ .Values.hostNetwork }}
{{- end }}
