{{- if and .Values.podDisruptionBudget.enabled (eq .Values.mode "deployment") }}
apiVersion: {{ include "podDisruptionBudget.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "otel-agent.fullname" . }}
  namespace: {{ template "otel-agent.namespace" . }}
  labels:
    {{- include "otel-agent.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end  }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end  }}
  selector:
    matchLabels:
      {{- include "otel-agent.selectorLabels" . | nindent 6 }}
{{- end }}
