{{- if and .Values.serviceMonitor.enabled .Values.serviceMonitor.metricsEndpoints (or (eq .Values.mode "deployment") (eq .Values.mode "statefulset")) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "otel-agent.fullname" . }}
  namespace: {{ template "otel-agent.namespace" . }}
  labels:
    {{- include "otel-agent.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.serviceMonitor.extraLabels }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "otel-agent.selectorLabels" . | nindent 6 }}
      {{- include "otel-agent.component" . | nindent 6 }}
  endpoints:
  {{- toYaml .Values.serviceMonitor.metricsEndpoints | nindent 2 }}
{{- end }}
