# Default values for mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  podAntiAffinityLabelSelector: []
  podAntiAffinityTermLabelSelector: []
  podAffinityLabelSelector: []
  podAffinityTermLabelSelector: []
  nodeAffinityLabelSelector: []
  nodeAffinityTermLabelSelector: []

replicas: 1

image:
  repository: public.ecr.aws/p8w3i6u3/mysql
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 8.4.0

timezone: "Etc/GMT"
hostNetwork: "false"
dnsPolicy: ClusterFirst
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
password: kubesense

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000
readinessProbe:
  tcpSocket:
    port: tcp
  failureThreshold: 6
  initialDelaySeconds: 15
  periodSeconds: 10
  successThreshold: 1
livenessProbe:
  failureThreshold: 6
  initialDelaySeconds: 15
  periodSeconds: 20
  successThreshold: 1
  tcpSocket:
    port: tcp
  timeoutSeconds: 1

chmodContainer:
  enabled: true
securityContext: {}
storageConfig:
  generateType: "{{ if $.Values.global.allInOneLocalStorage }}hostPath{{ else }}{{$.Values.storageConfig.type}}{{end}}" #Please ignore this
  ## persistentVolumeClaim/hostPath
  type: persistentVolumeClaim
  hostPath: /opt/kubesense-mysql
  persistence:
    storageClass: ""
    annotations:
      "helm.sh/resource-policy": keep
    # existingClaim: your-claim-pvc-name
    accessMode: ReadWriteOnce
    size: 50Gi 
    
externalMySQL:
  enabled: false
  hostIP: 192.168.1.1
  port: 3306

service:
  ## Configuration for Clickhouse service
  ##
  annotations: {}
  labels: {}
  clusterIP: ""

  ## Port for Clickhouse Service to listen on
  ##

  ports:
  - name: tcp
    port: 3306
    targetPort: 3306
    nodePort: 
    protocol: TCP
  ## Additional ports to open for server service
  additionalPorts: []

  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []

  ## Denotes if this Service desires to route external traffic to node-local or cluster-wide endpoints
  ## must be Local
  externalTrafficPolicy: Cluster

  ## Service type
  ##
  type: ClusterIP


resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
    cpu: 100m
    memory: 250Mi
  limits:
    cpu: 200m
    memory: 750Mi

nodeSelector: {}

tolerations: []

podAntiAffinityLabelSelector: []
podAntiAffinityTermLabelSelector: []
podAffinityLabelSelector: []
podAffinityTermLabelSelector: []
nodeAffinityLabelSelector: []
nodeAffinityTermLabelSelector: []

