apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeai.fullname" . }}
  labels:
    {{- include "kubeai.labels" . | nindent 4 }}
data:
  DB_USER: "{{ if $.Values.global.externalClickHouse.enabled }}{{ $.Values.global.externalClickHouse.username }}{{ else }}reader{{end}}"
  DB_HOST: "{{ if $.Values.global.externalClickHouse.enabled }}{{ $.Chart.Name }}-external-clickhouse{{ else }}{{ $.Release.Namespace }}-clickhouse-headless{{end}}:9000"
  DB_NAME: kube_trace
  PORT: "3003"
  OPENAI_MODEL: "gpt-3.5-turbo"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeai.fullname" . }}
  labels:
    {{- include "kubeai.labels" . | nindent 4 }}
stringData:
  OPENAI_API_KEY: "{{ $.Values.global.openai.apiKey }}"