apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeai.fullname" . }}
  labels:
    {{- include "kubeai.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 0
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kubeai.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubeai.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.global.image.pullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.global.image.pullSecrets }}
      {{- end }}
      serviceAccountName: {{ include "kubeai.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ tpl .Values.image.repository . }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ tpl .Values.image.pullPolicy . }}
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
          - configMapRef:
              name: {{ include "kubeai.fullname" . }}
          - secretRef:
              name: {{ include "kubeai.fullname" . }}
          {{- if .Values.env }}
          env:
          {{- with .Values.env }}
              {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - mountPath: "/etc/kubeai/public-key.pem"
            name: ssh-pub-key
            subPath: tls.crt
            readOnly: true
        - name: {{ .Chart.Name }}-chromadb
          image: chromadb/chroma:0.5.3
      volumes:
        - name: ssh-pub-key
          secret:
            secretName: "kubesense-certs"
            items:
            - key: tls.crt
              path: tls.crt            
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
      {{- include "nodeaffinity" . | indent 6 }}
      {{- include "podAffinity" . | indent 6 }}
      {{- include "podAntiAffinity" . | indent 6 }}
      {{- if or .Values.global.tolerations .Values.tolerations }}
      tolerations:
      {{- if .Values.global.tolerations }}
      {{- toYaml .Values.global.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- end }}
