apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeai.fullname" . }}
  labels:
    {{- include "kubeai.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "kubeai.selectorLabels" . | nindent 4 }}
