{{- if or (eq .Values.global.deploymentType "incluster") (eq .Values.global.deploymentType "server") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubecol.fullname" . }}-kubecol
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubecol.fullname" . }}-kubecol
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
    - ""
    resources:
      - endpoints
      - services
    verbs:
      - list
      - get
      - watch
      - create
      - update
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubecol.fullname" . }}-kubecol
subjects:
- kind: ServiceAccount
  name: {{ include "kubecol.fullname" . }}-kubecol
  namespace: {{ .Release.Namespace }}
  apiGroup: ""
roleRef:
  kind: Role
  name: {{ include "kubecol.fullname" . }}-kubecol
  apiGroup: ""
{{- end }}
