kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "kubesensor.fullname" . }}
  labels:
    {{- include "kubesensor.labels" . | nindent 4 }}
data:
  {{- tpl (toYaml .Values.kubesensorConfig) $ | nindent 2 }}