apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubesensor.cluterrolename" . }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubesensor.cluterrolename" . }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources:
  - nodes
  - namespaces
  - configmaps
  - services
  - pods
  - replicationcontrollers
  - persistentvolumes
  - persistentvolumeclaims
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs: ["get", "list", "watch"]
- apiGroups: ["","batch"]
  resources:
  - cronjobs
  - jobs
  verbs: ["get", "list", "watch"]  
# - apiGroups: ["batch/v1beta1"]
#   resources:
#   verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubesensor.cluterrolename" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubesensor.cluterrolename" . }}
  namespace: {{ .Release.Namespace }}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ include "kubesensor.cluterrolename" . }}
  apiGroup: ""
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubesensor.cluterrolename" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources:
  - configmaps
  resourceNames: ['{{ include "kubesensor.fullname" . }}']
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["apps"]
  resources:
  - daemonsets
  resourceNames: ['{{ include "kubesensor.fullname" . }}']
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubesensor.cluterrolename" . }}-role
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubesensor.cluterrolename" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "kubesensor.cluterrolename" . }}
  namespace: {{ .Release.Namespace }}
  apiGroup: ""