apiVersion: v1
kind: ConfigMap
metadata:
  name: vm-agent-aggregation-config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  aggregation_config.yaml: |
    - match: '{__name__=~"kubesense_.+_.+_counter|kubesense_unavailable_count", node_name!=""}'
      without: [node_name]
      interval: 30s
      outputs: [total]
      output_relabel_configs:
      - source_labels: [__name__]
        target_label: __name__
        regex: "(.+):.*"
        replacement: "$1"
    - match: '{__name__=~"^kubesense_.+latency_seconds$", node_name!=""}'
      without: [node_name]
      interval: 30s
      outputs: [avg]
      output_relabel_configs:
      - source_labels: [__name__]
        target_label: __name__
        regex: "(.+):.*"
        replacement: "$1"