{{- if .Values.global.enableSecretHook }}
{{- if or (eq .Values.global.deploymentType "incluster") (eq .Values.global.deploymentType "server") }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}-secret"
  labels:
    app: {{ template "ssl-cert.name" . }}
    chart: {{ template "ssl-cert.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install"
stringData:
  # CLICKHOUSE_PASSWORD: {{ include "passwords.clickhouse-password" . | b64enc | quote }}
  # REDIS_PASSWORD: {{ include "passwords.redis-password" . | b64enc | quote }}
  # MYSQL_PASSWORD:  {{ include "passwords.mysql-password" . | b64enc | quote }}
  CLICKHOUSE_PASSWORD: "{{ if $.Values.global.externalClickHouse.enabled }}{{$.Values.global.externalClickHouse.password}}{{ else }}{{ $.Values.global.clickhouse.password }}{{end}}"
  REDIS_PASSWORD: "{{ if $.Values.global.externalRedis.enabled }}{{ $.Values.global.externalRedis.password }}{{ else }}{{ $.Values.global.redis.password }}{{ end }}"
  MYSQL_PASSWORD: "{{ if $.Values.global.externalMySQL.enabled }}{{$.Values.global.externalMySQL.password}}{{ else }}{{ $.Values.global.mysql.password }}{{end}}"
{{- end -}}
{{- end -}}