{{- if or (eq .Values.global.deploymentType "incluster") (eq .Values.global.deploymentType "server") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 0
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "api.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.global.image.pullSecrets }}
      imagePullSecrets:
        - name: {{ tpl .Values.global.image.pullSecrets . }}
      {{- end }}
      serviceAccountName: {{ include "api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      initContainers:
        {{ include "api.initContainers" . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ tpl .Values.api.image.repository . }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ tpl .Values.api.image.pullPolicy . }}
          ports:
            - name: {{ .Values.api.service.name }}
              containerPort: {{ .Values.api.service.port }}
              protocol: TCP
          {{- if .Values.api.env }}
          env:
          {{- with .Values.api.env }}
              {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- end }}
          envFrom:
          - configMapRef:
              name: {{ include "api.fullname" . }}
          - secretRef:
              name: {{ include "api.fullname" . }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          volumeMounts:
          - mountPath: "/opt/tyke/keys/grafana.key"
            name: ssh-private-key
            subPath: tls.key
            readOnly: true
      volumes:
        - name: ssh-private-key
          secret:
            secretName: "kubesense-certs"
            items:
            - key: tls.key
              path: tls.key
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
      {{- include "nodeaffinity" . | indent 6 }}
      {{- include "podAffinity" . | indent 6 }}
      {{- include "podAntiAffinity" . | indent 6 }}
      {{- if or .Values.global.tolerations .Values.tolerations }}
      tolerations:
      {{- if .Values.global.tolerations }}
      {{- toYaml .Values.global.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- end }}
{{- end }}
