{{- if or (eq .Values.global.deploymentType "incluster") (eq .Values.global.deploymentType "server") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.serviceType }}
  ports:
    - port: {{ .Values.api.service.port }}
      protocol: TCP
      name: {{ .Values.api.service.name }}
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}
{{- end }}
