{
 "title": "Kubernetes Cluster Resources",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": "prometheus" },
   {
    "name": "node",
    "query": {
     "query": "label_values(kubesense_node_m_cpu_usage_seconds_total{}, k8s_node_name)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kubesense_resource_total_counter{type=\"container_info\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "<div align=\"center\" style=\"text-align: center\" style=\"background-color:aquamarine;\">\n    <img  src=\"https://miro.medium.com/max/600/1*Xyrmr3lIfdwwH638Iv0LzQ.png\" width=\"65%\" title=\"kubesense\" />\n</div>"
   }
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (k8s_node_name) (rate(kubesense_node_m_cpu_usage_seconds_total{k8s_node_name=~'$node'}[60s]))) / sum(sum by (k8s_node_name) (kubesense_node_allocatable_cpum_cpu{k8s_node_name=~'$node'})) "
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (k8s_node_name) (kubesense_node_mem_working_set_bytes{k8s_node_name=~'$node'})) / sum(sum by (k8s_node_name) (kubesense_node_allocatable_mem_bytes{k8s_node_name=~'$node'}))"
    }
   ]
  },
  {
   "title": "🔹 Nodes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (k8s_node_name) (kubesense_node_m_cpu_usage_seconds_total{}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🔹 Workloads",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (workload) (kubesense_container_m_cpu_usage_seconds_total{}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🔹 Pods",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (pod) (kubesense_container_m_cpu_usage_seconds_total{}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🔹 Containers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (pod, container) (kubesense_container_m_cpu_usage_seconds_total{}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": " 🎚  CPU Usage (by Node)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mCPU" } },
   "targets": [
    {
     "expr": "topk(50, sum by (k8s_node_name) (rate(kubesense_node_m_cpu_usage_seconds_total{k8s_node_name=~'$node'}[60s])))* 1000",
     "legendFormat": "__auto",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": " 🔺  CPU usage % by Node",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (k8s_node_name) (rate(kubesense_node_m_cpu_usage_seconds_total{k8s_node_name=~'$node'}[60s])) / sum by (k8s_node_name) (kubesense_node_allocatable_cpum_cpu{k8s_node_name=~'$node'}))",
     "legendFormat": "{{k8s_node_name}}"
    }
   ]
  },
  {
   "title": "🧠 Memory Usage (by Node)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(k8s_node_name) (kubesense_node_mem_working_set_bytes{k8s_node_name=~'$node'})",
     "legendFormat": "{{k8s_node_name}}"
    }
   ]
  },
  {
   "title": "🔺 Memory usage % by Node",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, max(kubesense_node_mem_working_set_bytes{}) by (k8s_node_name) / max(kubesense_node_allocatable_mem_bytes{}) by (k8s_node_name)* 100)",
     "legendFormat": "{{ k8s_node_name }}"
    }
   ]
  },
  {
   "title": "💾 Disk Usage (by Node)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(k8s_node_name) (kubesense_node_disk_space_used_bytes{k8s_node_name=~'$node'})",
     "legendFormat": "{{k8s_node_name}}"
    }
   ]
  },
  {
   "title": "🔺 Disk usage % by Node",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(kubesense_node_disk_space_used_bytes{}) by (k8s_node_name) / max(kubesense_node_disk_space_total_bytes{}) by (k8s_node_name)) * 100",
     "legendFormat": "{{ k8s_node_name }}"
    }
   ]
  },
  {
   "title": "Workloads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": " 🎚  CPU Usage (by Workload)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "mCPU" } },
   "targets": [
    {
     "expr": "topk(50, sum by (namespace, workload) (rate(kubesense_container_m_cpu_usage_seconds_total{namespace=~'$namespace',workload!=\"\"}[60s]))) * 1000",
     "legendFormat": "{{workload}}  ➜ {{namespace}}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "🔺 Most CPU Intensive (by Workload)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "mCPU" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (workload, namespace) (rate(kubesense_container_m_cpu_usage_seconds_total{namespace=~'$namespace',workload!=\"\"}[60s]))) * 1000",
     "legendFormat": "{{workload}} "
    }
   ]
  },
  {
   "title": "🧠 Memory Usage (by Workload)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(50, sum by (namespace, workload) (kubesense_container_mem_working_set_bytes{namespace=~'$namespace',workload!=\"\"}))",
     "legendFormat": "{{workload}}  ➜ {{namespace}}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "🔺 Most Memory Intensive (by Workload)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (workload, namespace) (kubesense_container_mem_working_set_bytes{namespace=~'$namespace',workload!=\"\"}))",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  { "title": "Persistent Storage Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "💾 Persistent Volume Storages",
   "type": "table",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kubesense_pvc_capacity_bytes{namespace=~'$namespace'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kubesense_pvc_usage_bytes{namespace=~'$namespace'}/ kubesense_pvc_capacity_bytes{namespace=~'$namespace'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " 🔺   Most Utilized PVCs",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(15, (max(kubesense_pvc_usage_bytes{namespace=~'$namespace',persistentvolumeclaim!=\"\"}) by (persistentvolumeclaim)/ max(kubesense_pvc_capacity_bytes{namespace=~'$namespace',persistentvolumeclaim!=\"\"}) by (persistentvolumeclaim)) * 100)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}